include functions
unit test

colors

diff --git a/test/test-all b/test/test-all
--- a/test/test-all
+++ b/test/test-all
@@ -1,51 +1,90 @@
 #!/bin/bash
 
-
+#CONSTANTS
 GREEN="\e[32m"
 RED="\e[91m"
 MAG="\e[35m"
+YEL="\e[33m"
 RSTCOLOR="\e[0m"
 
 # input
+ARGV=$@
+exe="./test"
 MFILEPATH="../bytecodes"
-rm -rf tmp
-mkdir tmp
-for file in $MFILEPATH/*
-do
-	MFILE=$(echo ${file} | cut -d '/' -f3)
-	if [[ $MFILE == 'README.md' ]]; then
-		continue
+
+function main {
+	#CLEAN WORKSPACE
+	rm -rf tmp
+	mkdir tmp
+
+	if ! [ -f "$exe" ]; then
+		echo "$exe not found. Use make to create it"
+		exit
 	fi
 
-	exe="./test"
+	if [[ $# -eq 0 ]]; then
+		echo "NO ARGS"
+		DETAILS=false
+		multitest
+	else
+		echo "ARGS"
+		DETAILS=true
+		unittest $1
+	fi
+}
+
+function unittest {
+	MFILE=$1
 	OFILE=$(echo "stdout-${MFILE%.m}")
 	OPATH=$(echo "./tmp/$OFILE")
-	RFILE="expected-${MFILE%.m}"
 
+	RFILE="expected-${MFILE%.m}"
 	RFILEPATH="./expected-out"
 	MFILEPATH="../bytecodes"
 
 	FPATH_MFILE="$MFILEPATH/$MFILE"
 	FPATH_RFILE="$RFILEPATH/$RFILE"
 
-
 	printf "$MFILE: "
 	cmd="$exe $MFILEPATH/$MFILE"
 	eval $cmd &> $OPATH
-	if [[ -f "$FPATH_RFILE" ]]; then
+	if [ -f "$FPATH_RFILE" ]; then
 		if cmp -s $OPATH $FPATH_RFILE; then
-			printf $GREEN"OK"$RSTCOLOR
+			printf $GREEN"OK\n"$RSTCOLOR
+			TMPCOLOR=$GREEN
 		else
 			printf $RED"FAILED\n"$RSTCOLOR
-			echo "----------------"
-			echo "[GOT]"
-			cat $OPATH
-			echo "[EXPECTED]"
-			cat $FPATH_RFILE
-			echo "------------------"
+			TMPCOLOR=$RED
 		fi
 	else
-		printf $MAG"NO_REF"$RSTCOLOR
+		printf $MAG"NO_REF\n"$RSTCOLOR
+		TMPCOLOR=$MAG
 	fi
-	printf "\n"
-done
+
+	if [ $DETAILS == true ]; then
+		echo "------------------"
+		printf "[${TMPCOLOR}GOT${RSTCOLOR}]\n"
+		cat $OPATH
+		printf "[${TMPCOLOR}EXPECTED${RSTCOLOR}]\n"
+		cat $FPATH_RFILE
+		echo "------------------"
+		printf "\n"
+	fi
+
+}
+
+function multitest {
+	for file in $MFILEPATH/*
+	do
+		MFILE=$(echo ${file} | cut -d '/' -f3)
+		if [[ $MFILE == 'README.md' ]]; then
+			continue
+		fi
+
+		unittest $MFILE
+
+	done
+}
+
+#RUNNING PROGRAM HERE
+main $ARGV
